// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql_model

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}
