package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"go_test/graph/gql_model"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, title string, content string, author string) (*gql_model.Post, error) {
	return r.postResolver.CreatePost(ctx, title, content, author)
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id string, title *string, content *string) (*gql_model.Post, error) {
	return r.postResolver.UpdatePost(ctx, id, title, content)
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (*gql_model.Post, error) {
	return r.postResolver.DeletePost(ctx, id)
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*gql_model.Post, error) {
	return r.postResolver.Post(ctx, id)
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*gql_model.Post, error) {
	return r.postResolver.Posts(ctx)
}
